development:
  adapter: postgresql
  encoding: unicode
  database: cup2cup_development
  pool: 5
  username: kellywaters 
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: cup2cup_test
  pool: 5
  username: kellywaters
  password: 