# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26afee7e3c0ffcbcba8dfdef388cba749af488c5d3aae4f9e6aafeb282dcc4e1faf557c46ff2bcf1c6fe17f17760109603ae5e3d8bd5d9fba840be1fed7d1601

test:
  secret_key_base: 43c2c10e764cc3443c4d70aed0247f1fe390210cb97f377908d86a32daa8b9ce5b386172c70b614e68cb9daa2e9e753c1f8c27cc73c2103a8d9298d63e520049

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
